name: cost-report

on:
  workflow_call:
    inputs:
      path:
        description: "Path (inside the repo) that contains .agent/ledger.json"
        required: false
        default: "."
        type: string

jobs:
  cost:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print token totals from .agent/ledger.json (skip if absent)
        shell: bash
        run: |
          cd "${{ inputs.path }}"
          if [ ! -f .agent/ledger.json ]; then
            echo "No .agent/ledger.json found; skipping."
            exit 0
          fi
          # jq is available on ubuntu-latest; if not, uncomment next line:
          # sudo apt-get update && sudo apt-get install -y jq
          pts=$(jq '[.[] | .prompt_tokens // 0] | add // 0' .agent/ledger.json)
          cts=$(jq '[.[] | .completion_tokens // 0] | add // 0' .agent/ledger.json)
          echo "Total prompt tokens: $pts"
          echo "Total completion tokens: $cts"
