name: opa
on:
  workflow_call:
jobs:
  opa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install conftest
        run: |
          curl -sL https://github.com/open-policy-agent/conftest/releases/latest/download/conftest_$(uname -s)_$(uname -m).tar.gz -o conftest.tgz
          mkdir -p ~/bin
          tar -xzf conftest.tgz -C ~/bin
          echo "$HOME/bin" >> $GITHUB_PATH
      - name: Run conftest
        run: |
          conftest test policy/ || true
