name: opa
on:
  workflow_call:
jobs:
  opa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install conftest
        run: |
          VERSION=$(curl -s https://api.github.com/repos/open-policy-agent/conftest/releases/latest | jq -r .tag_name)
          OS=$(uname -s | tr '[:upper:]' '[:lower:]')
          ARCH=$(uname -m)
          curl -sL https://github.com/open-policy-agent/conftest/releases/download/${VERSION}/conftest_${OS}_${ARCH}.tar.gz -o conftest.tgz
          mkdir -p ~/bin
          tar -xzf conftest.tgz -C ~/bin
          echo "$HOME/bin" >> $GITHUB_PATH
      - name: Run conftest
        run: |
          conftest test policy/ || true
