name: opa
on:
  workflow_call:
jobs:
  opa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install conftest
        run: |
          set -euo pipefail
          # Find the Linux x86_64 tarball from the latest release
          REL_JSON="$(curl -s https://api.github.com/repos/open-policy-agent/conftest/releases/latest)"
          URL="$(echo "$REL_JSON" | jq -r '.assets[] | select(.name | test("Linux_x86_64\\.tar\\.gz$")) | .browser_download_url')"
          echo "Downloading: $URL"
          curl -sL "$URL" -o conftest.tgz
          mkdir -p ~/bin
          tar -xzf conftest.tgz -C ~/bin
          ~/bin/conftest --version
          echo "$HOME/bin" >> $GITHUB_PATH
      - name: Run conftest
        run: |
          conftest test policy/ || true
