name: publish-v1
on:
  push:
    branches: [ main ]

jobs:
  retag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Move v1 tag to latest main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # Create/force-move lightweight major tag
          git tag -f v1
          git push -f origin v1
