name: security
on:
  workflow_call:
jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: semgrep scan (basic)
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/ci
