name: spec-check
on:
  workflow_call:
jobs:
  spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fail if [NEEDS CLARIFICATION] remains
        run: |
          if grep -R "\[NEEDS CLARIFICATION" -n specs/ ; then
            echo "Unresolved clarifications."; exit 1; fi
      - name: Phase –1 gates present
        run: |
          if ! grep -R "Phase –1 Gates" -n specs/ ; then
            echo "Phase –1 gates missing."; exit 1; fi
